source 'http://rubygems.org'

gem 'sinatra'
gem 'heroku'
gem 'rack-parser'
gem 'rabl'
gem 'sinatra-activerecord'
gem 'activerecord'
gem 'pg'
gem 'rack-throttle'
gem 'dalli'
gem 'redis'
gem 'resque'
gem 'unicorn'
gem 'mongoid'
gem 'bson'
gem 'bson_ext', "~> 1.3"
